---
- name: Setup of Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC Setup Variable
      include_vars: vars/output_vars

    - name: Import Vprofile Setup Variable
      include_vars: vars/vpc_output_vars

    - name: Create Vprofile EC2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: vprofilekey_out

    - name: Save Private Key Into File ec2key_pair.pem
      copy:
        content: "{{vprofilekey_out.key.private_key}}"
        dest: "./ec2key_pair.pem"
        mode: 0600
      when: vprofilekey_out.changed
