---
- name: Build Artifacts ROOT.war and SQL File to be copied in files/directory
  import_playbook: build.yml

- name: Set Hosts to Ip Mapping in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on DBserver
  import_playbook: dbdeploy.yml

- name: Setup Memcache Service
  import_playbook: memcache.yml

- name: Setup rabbitmq service
  import_playbook: rabbitmq.yml

- name: Setup Tomcat application server
  import_playbook: appserver.yml

- name: Setup nginx server
  import_playbook: web.yml
